package sqlparser

import (
	"encoding/json"
	"strings"
	"testing"
)

func TestRewriteEdgeSqls(t *testing.T) {
	typeMap := map[string]map[string]string{
		"shop_sim": {
			"order_rate_weight": "double",
		},
		"sim_author": {
			"order_rate_weight": "double",
			"property2":         "double",
		},
		"shop_strong_group": {},
	}
	rewritten, err := RewriteSqls(`SELECT  DISTINCT point1_id,
        point2_id,
        point1_type,
        point2_type,
        value,
        ts_us,
        edge_type,
        cast(order_rate_weight as float),
		low_score_author_cnt
FROM    (
        SELECT  src AS point1_id,
                tgt AS point2_id,
                'shop' AS point1_type,
                'sim' AS point2_type,
                '' AS value,
                (UNIX_TIMESTAMP() * 1000000) AS ts_us,
                'shop_sim' AS edge_type,
               ratio_src AS order_rate_weight
        FROM    dm_temai.shop_gandalf_v1_3_graph_structure_di
        WHERE   date = max_pt('dm_temai.shop_gandalf_v1_3_graph_structure_di')
        AND     edge_type = 'shop_sell_sim_1d'
        ) a;

SELECT  DISTINCT point1_id,
        point2_id,
        point1_type,
        point2_type,
        value,
        ts_us,
        edge_type,
        cast(order_rate_weight as double),
        property2
FROM    (
        SELECT  src AS point2_id,
                tgt AS point1_id,
                'author' AS point2_type,
                'sim' AS point1_type,
                '' AS value,
                (UNIX_TIMESTAMP() * 1000000) AS ts_us,
                'sim_author' AS edge_type,
                ratio_src AS order_rate_weight,
                'prop' AS property2
        FROM    dm_temai.shop_gandalf_v1_3_graph_structure_di
        WHERE   date = max_pt('dm_temai.shop_gandalf_v1_3_graph_structure_di')
        AND     edge_type = 'author_sell_sim_1d'
        ) a;

SELECT  concat(link_type, '_', CAST(group_id AS STRING)) AS point1_id,
        CAST(entity_id AS STRING) AS point2_id,
        'group' AS point1_type,
        'shop' AS point2_type,
        UNIX_TIMESTAMP() * 1000000 AS ts_us,
        concat(link_type, '_', 'group') AS edge_type
FROM    ecom_govern_community.group_few_shot_base_link_devide_group
WHERE   date = max_pt('ecom_govern_community.group_few_shot_base_link_devide_group')
AND     link_type IN (
        'shop_strong',
        'shop_pledgeId',
        'shop_oceadId',
        'shop_mobile',
        'shop_idCard',
        'shop_highprec',
        'shop_chargeMobile',
        'shop_bizNum',
        'shop_bank',
        'shop_aftersaleMobile',
        'shop_90dSendAddrGh8',
        'shop_90dProductBindAuthor',
        'shop_90dOrderProductSimNew',
        'shop_90dOrderAuthor',
        'shop_90dLoginIp',
        'shop_90dLoginDid',
        'shop_90dCreateProductSimNew'
);`, false, typeMap)
	if err != nil {
		t.Fatalf("RewriteSqls error: %v", err)
	}
	if len(rewritten) != 3 {
		t.Fatalf("expected 3 rewritten sqls, got %d", len(rewritten))
	}
	if _, ok := rewritten["shop_strong_group"]; !ok {
		t.Fatalf("expected rewritten sql for shop_strong_group edge type")
	}

	buffer, _ := json.MarshalIndent(rewritten, "", "  ")
	t.Log("\n" + string(buffer))
}

func TestRewriteEdgeSqlUnion(t *testing.T) {
	sql := `SELECT  CAST(entity_a AS STRING) AS point1_id,
    CAST(entity_b AS STRING) AS point2_id,
    'shop' AS point1_type,
    'shop' AS point2_type,
    UNIX_TIMESTAMP() * 1000000 AS ts_us,
    'shop_shop_relation' AS edge_type,
    link_info['idCard'] AS idCard,
    link_info['bizNum'] AS bizNum,
    link_info['bank'] AS bank,
    link_info['pledgeId'] AS pledgeId,
    link_info['mobile'] AS mobile,
    link_info['chargeMobile'] AS chargeMobile,
    link_info['aftersaleMobile'] AS aftersaleMobile,
    link_info['loginDid'] AS loginDid,
    link_info['loginIp'] AS loginIp,
    link_info['sendAddr'] AS sendAddr,
    link_info['strong'] AS strong,
    link_info['highprec'] AS highprec,
    link_info['fusionLink'] AS fusionLink,
    link_info['productBindAuthor'] AS productBindAuthor,
    link_info['orderAuthor'] AS orderAuthor,
    link_info['createProductSim'] AS createProductSim,
    link_info['orderProductSim'] AS orderProductSim
FROM  dm_temai.ecom_entity_homolink_bg
WHERE   date = max_pt('dm_temai.ecom_entity_homolink_bg')
AND   link_type = 'shop_shop'
AND   entity_a IS NOT NULL
AND   entity_b IS NOT NULL;

SELECT  CAST(entity_b AS STRING) AS point1_id,
    CAST(entity_a AS STRING) AS point2_id,
    'shop' AS point1_type,
    'shop' AS point2_type,
    UNIX_TIMESTAMP() * 1000000 AS ts_us,
    'shop_shop_relation' AS edge_type,
    link_info['idCard'] AS idCard,
    link_info['bizNum'] AS bizNum,
    link_info['bank'] AS bank,
    link_info['pledgeId'] AS pledgeId,
    link_info['mobile'] AS mobile,
    link_info['chargeMobile'] AS chargeMobile,
    link_info['aftersaleMobile'] AS aftersaleMobile,
    link_info['loginDid'] AS loginDid,
    link_info['loginIp'] AS loginIp,
    link_info['sendAddr'] AS sendAddr,
    link_info['strong'] AS strong,
    link_info['highprec'] AS highprec,
    link_info['fusionLink'] AS fusionLink,
    link_info['productBindAuthor'] AS productBindAuthor,
    link_info['orderAuthor'] AS orderAuthor,
    link_info['createProductSim'] AS createProductSim,
    link_info['orderProductSim'] AS orderProductSim
FROM  dm_temai.ecom_entity_homolink_bg
WHERE   date = max_pt('dm_temai.ecom_entity_homolink_bg')
AND   link_type = 'shop_shop'
AND   entity_a IS NOT NULL
AND   entity_b IS NOT NULL;`

	rewritten, err := RewriteSqls(sql, true, nil)
	if err != nil {
		t.Fatalf("RewriteSqls error: %v", err)
	}

	if len(rewritten) != 1 {
		t.Fatalf("expected 1 rewritten sql, got %d", len(rewritten))
	}

	def, ok := rewritten["shop_shop_relation"]
	if !ok {
		t.Fatalf("expected key shop_shop_relation in rewritten map")
	}

	lower := strings.ToLower(def.Sql)
	if !strings.Contains(lower, "union all") {
		t.Fatalf("expected union all in rewritten sql, got %s", def.Sql)
	}

	if strings.Count(lower, "row_number()") != 1 {
		t.Fatalf("expected single deduplication step, got %s", def.Sql)
	}

	t.Log(def.Sql)
}

func TestRewritePointSql(t *testing.T) {
	rewritten, err := RewriteSqls(`SELECT
concat(leaf_cid_new, '-', price_range_in) AS point_id,
        'leaf' AS point_type,
        concat(leaf_cid_new, '-', price_range_in) AS point_value,
  concat(leaf_cid_new, '-', price_range_in) as leaf_price,
  price_range_in,
  price_ranges[0] AS price_1_pt,
  price_ranges[1] AS price_5_pt,
  price_ranges[2] AS price_10_pt,
  price_ranges[3] AS price_25_pt,
  price_ranges[4] AS price_50_pt,
  price_ranges[5] AS price_75_pt,
  price_ranges[6] AS price_90_pt,
  price_ranges[7] AS price_95_pt,
  price_ranges[8] AS price_99_pt,
  cast(order_cnt as double),
  cast(ccr_order_cnt as double),
  cast(quality_ccr_order_cnt as double),
  cast(content_ccr_order_cnt as double),
  cast(service_ccr_order_cnt as double),
  cast(p0_ccr_order_cnt as double),
  cast(bad_comment_order_cnt as double),
  cast(good_comment_order_cnt as double),
  cast(quality_return_order_cnt as double),
  cast(complaint_order_cnt as double),
  cast(shop_cnt as double),
  cast(author_cnt as double),
  cast(product_cnt as double),
  cast(banned_product_cnt as double),
  cast(delete_product_cnt as double),
  cast(clear_shop_cnt as double),
  cast(low_level_shop_cnt as double),
  cast(low_score_shop_cnt as double),
  cast(low_score_author_cnt as double),
  cast(no_auth_author_cnt as double),
  cast(low_level_author_cnt as double),
  cast(comment_order_cnt as double),
  ccr_ratio,
  quality_ccr_ratio,
  content_ccr_ratio,
  service_ccr_ratio,
  p0_ccr_ratio,
  bad_comment_ratio,
  good_comment_ratio,
  quality_return_order_ratio,
  complaint_order_ratio,
  banned_product_ratio,
  delete_product_ratio,
  clear_shop_ratio,
  low_level_shop_ratio,
  low_score_shop_ratio,
  no_auth_author_ratio,
  low_score_author_ratio,
  low_level_author_ratio
FROM
  dm_temai.shop_price_range_ccr_negative_new_30d
WHERE date = max_pt('dm_temai.shop_price_range_ccr_negative_new_30d')`, false, map[string]map[string]string{
		"group": {
			"quality_ccr_cnt_60d": "float",
		},
	})
	if err != nil {
		t.Fatalf("RewriteSqls error: %v", err)
	}
	if len(rewritten) != 1 {
		t.Fatalf("expected 1 rewritten sql, got %d", len(rewritten))
	}

	buffer, _ := json.MarshalIndent(rewritten, "", "  ")
	t.Log("\n" + string(buffer))
}

func TestRewritePointSqls(t *testing.T) {
	rewritten, err := RewriteSqls(`WITH total_shop_id_table AS (
  SELECT  DISTINCT (shop_id)
  FROM  (
        SELECT  shop_id
        FROM  dm_temai.shop_govern_group_stats_for_groupgdfv1 t1
        WHERE   date = max_pt('dm_temai.shop_govern_group_stats_for_groupgdfv1')
        UNION ALL
        SELECT  shop_id
        FROM  dm_temai.group_few_shot_shop_node_feature
        WHERE   date = max_pt('dm_temai.group_few_shot_shop_node_feature')
      )
),
shop_gandalf_property AS (
  SELECT  shop_id,
      quality_return_model,
      low_penanlize_cnt_td,
      fake_severity_penanlize_cnt_td,
      shop_quality_ccr_alld_14d,
      ban_severity_penanlize_cnt_td,
      audit_success_product_cnt_td,
      shop_quality_ccr_order_cnt_14d,
      create_ucnt_1d,
      g_deport_cnt,
      shop_quality_ccr_14d,
      g_selfemployed_cnt,
      shop_level,
      create_gmv_1d,
      out_times,
      bad_eval_model,
      shop_quality_ccr_7d,
      g_suspend_cnt,
      g_size,
      g_bad_eval_rate_30d,
      reject_verify_access_pdc,
      g_bad_eval_rate_7d,
      all_severity_penanlize_cnt_td,
      g_open_cnt,
      shop_quality_ccr_order_cnt_44d_14d,
      create_product_cnt_td,
      low_penanlize_cnt_180d,
      audit_success_product_cnt_7d,
      saled_refund_order_rate_td,
      shop_order_cnt_alld_14d,
      launch,
      shop_quality_ccr_3d,
      hit_repeat_distribution_cnt_7d,
      received_order_cnt_7d,
      aftersale_ccr_14d,
      fake_shop_penanlize_cnt_td,
      shop_quality_ccr_order_cnt_7d,
      g_shop_level_1_cnt,
      shop_ccr_alld_14d,
      aftersale_ccr_7d,
      shop_order_cnt_14d,
      cancel_order_rate_td,
      g_shop_level_2_cnt,
      ontime_order_rate_td,
      is_novice_village,
      shop_order_cnt_3d,
      v_type,
      avg_new_response_time_td,
      shop_quality_ccr_44d_14d,
      shop_content_ccr_7d,
      quality_refund_rate_td,
      shop_quality_ccr_28d_14d,
      is_self_live,
      g_product_ban_cnt,
      shop_quality_ccr_order_cnt_28d_14d,
      class,
      g_enterprise_cnt,
      satisfaction_rate_1d,
      shop_type,
      pay_order_rate_7d,
      pay_product_cnt_1d AS pay_product_cnt_1d_,
      shop_content_ccr_alld_14d AS shop_content_ccr_alld_14d_,
      shop_quality_ccr_order_cnt_alld_14d AS shop_quality_ccr_order_cnt_alld_14d_,
      shop_quality_ccr_21d_14d AS shop_quality_ccr_21d_14d_,
      content_cmn_cnt_21d AS content_cmn_cnt_21d_,
      g_hit_repeat_distribution_cnt_7d,
      received_order_cnt_1d,
      complain_rate_td,
      intime_res_con_rate_td,
      pay_order_rate_td,
      g_saled_refund_order_rate_30d,
      pay_order_rate_30d,
      saling_refund_sucess_order_rate_td,
      g_total_penalize_cnt,
      shop_order_cnt_44d_14d,
      avg_new_response_time_30d,
      aftersale_ccr_30d,
      cancel_order_rate_30d,
      shop_service_ccr_7d,
      shop_service_21d,
      shop_order_cnt_28d_14d,
      function_properties_21d,
      g_hit_repeat_distribution_cnt_30d,
      complaint_model,
      shop_quality_ccr_order_cnt_21d_14d,
      div_7d,
      im_message_ccr_7d,
      verify_recall_pdc_7d,
      hit_repeat_distribution_cnt_1d,
      verify_recall_pdc,
      shop_ccr_3d,
      product_bad_eval_rate_td,
      complain_rate_30d,
      saling_refund_order_rate_td,
      ontime_order_rate_7d,
      all_shop_penanlize_cnt_td,
      saled_refund_order_rate_30d,
      aftersale_ccr_90d,
      aftersale_ccr_60d,
      shop_order_cnt_21d_14d,
      shop_quality_ccr_order_cnt_3d,
      all_severity_penanlize_cnt_180d,
      cancel_order_rate_7d,
      before_44d_14d_quality_refund_rate,
      goods_not_confirm_7d,
      pay_ucnt_1d,
      pay_product_cnt_30d,
      saling_refund_order_rate_30d,
      hit_repeat_distribution_cnt_30d,
      comment_ccr_7d,
      bad_eval_rate_td,
      g_saled_refund_order_rate_7d,
      video_cnt,
      shop_service_bad_eval_rate_td,
      shop_content_ccr_44d_14d,
      expect_delivery_order_cnt_1d,
      shop_settle_type,
      saling_refund_ucnt_1d,
      pay_product_cnt_7d,
      saling_refund_gmv_1d,
      logistic_bad_eval_rate_td,
      saling_refund_sucess_order_rate_7d,
      g_good_eval_rate_30d,
      pay_combo_num_30d,
      abnormal_pay_gmv_td,
      create_order_cnt_1d,
      ban_severity_penanlize_cnt_180d,
      bad_eval_rate_30d,
      report_video_ratio,
      hit_repeat_distribution_cnt_td,
      light_score,
      cancel_order_cnt_7d,
      function_properties_7d,
      shop_content_ccr_21d_14d,
      service_behavior_21d,
      video_check_reject_ratio,
      pay_gmv_1d,
      saled_refund_order_rate_1d,
      quality_refund_order_cnt_7d,
      logistic_bad_eval_rate_30d,
      cancel_ucnt_1d,
      pay_product_cnt_td,
      shop_service_ccr_order_cnt_14d,
      shop_ccr_7d,
      combo_average_price_td,
      total_alliance_promote_product_cnt,
      intime_res_con_rate_30d,
      shop_content_ccr_order_cnt_44d_14d,
      saled_refund_order_rate_7d,
      pay_combo_num_1d,
      logistic_bad_eval_rate_7d,
      shop_content_ccr_order_cnt_14d,
      all_severity_penanlize_cnt_60d,
      satisfaction_rate_td,
      shop_service_ccr_alld_14d,
      shop_content_ccr_28d_14d,
      ontime_order_rate_30d,
      shop_author_cnt,
      reject_verify_access_pdc_7d,
      total_alliance_promoted_product_cnt,
      avg_watch_duration_30d,
      shop_ccr_order_cnt_3d,
      shop_service_7d,
      all_shop_penanlize_cnt_180d,
      shop_service_bad_eval_rate_30d,
      shop_content_ccr_order_cnt_7d,
      ban_product_cnt_30d,
      cancel_order_rate_1d,
      create_gmv_30d,
      aftersale_fake_ccr_60d,
      shop_service_ccr_3d,
      before_21d_14d_quality_refund_rate,
      abnormal_pay_order_cnt_td,
      ccr_7d,
      user_average_price_td,
      shop_content_ccr_14d,
      comment_ccr_180d,
      received_order_cnt_30d,
      rescan,
      video_check_reject_cnt,
      content_cmn_cnt_7d,
      verify_access_pdc,
      saling_refund_sucess_order_rate_30d,
      logistic_good_eval_rate_td,
      im_message_ccr_60d,
      low_penanlize_cnt_90d,
      verify_access_pdc_7d,
      promo_fraud_21d,
      saling_refund_sucess_order_rate_1d,
      low_penanlize_cnt_30d,
      shop_author_cnt_l5_30d,
      shop_service_ccr_44d_14d,
      shop_ccr_order_cnt_7d,
      product_bad_eval_rate_30d,
      bad_eval_rate_7d,
      saling_refund_sucess_ucnt_1d,
      target_ave_cnt,
      subjective_feeling_7d,
      shop_ccr_44d_14d,
      avg_new_response_time_7d,
      quality_refund_order_cnt_td,
      im_message_ccr_30d,
      shop_service_ccr_21d_14d,
      complain_cnt_td,
      shop_service_ccr_order_cnt_7d,
      audit_success_product_cnt_30d,
      saled_refund_order_cnt_30d,
      shop_ccr_14d,
      reject_verify_recall_pdc_30d,
      true_report_room_cnt,
      cancel_order_cnt_td,
      shop_service_good_eval_rate_td,
      expect_delivery_order_cnt_30d,
      saling_refund_order_cnt_30d,
      ban_product_cnt_td,
      reject_verify_recall_pdc,
      strong_copy_pdc,
      comment_ccr_90d,
      saled_refund_sucess_order_cnt_30d,
      ban_product_cnt_7d,
      forward_logistics_21d,
      shop_author_cnt_7d,
      saling_refund_sucess_gmv_1d,
      im_message_ccr_90d,
      video_cnt_7d,
      cl_inlive_cancel_cnt_30d,
      all_shop_penanlize_cnt_90d,
      pay_order_rate_1d,
      shop_content_ccr_order_cnt_alld_14d,
      weak_copy_pdc,
      quality_refund_order_cnt_30d,
      avg_watch_duration_7d,
      consumer_complaint_7d,
      satisfaction_rate_7d,
      fake_ship_order_rate_td,
      product_good_eval_rate_td,
      cancel_order_cnt_1d,
      cl_inlive_cancel_cnt_7d,
      saling_refund_order_rate_7d,
      pay_combo_num_7d,
      reject_verify_access_pdc_30d,
      create_product_cnt_7d,
      video_cnt_30d,
      saling_refund_order_cnt_td,
      complain_cnt_7d,
      saled_refund_order_cnt_7d,
      cancel_order_cnt_30d,
      shop_ccr_28d_14d,
      std,
      delivery_order_cnt_7d,
      saling_refund_order_rate_1d,
      before_44d_14d_order_cnt,
      shop_service_ccr_14d,
      bad_comment_ratio_30d_2_pdc,
      saled_refund_gmv_1d,
      shop_author_cnt_l5,
      g_good_eval_rate_7d,
      illegal_selling_21d,
      shop_ccr_21d_14d,
      rescan_roll,
      customer_experience_7d,
      user_average_price_7d,
      shop_ccr_order_cnt_14d,
      avg_new_response_time_1d,
      total_freeze_times_30d,
      user_average_price_30d,
      verify_recall_pdc_30d,
      shop_author_cnt_l5_7d,
      consumer_complaint_21d,
      cancel_gmv_td,
      shop_author_cnt_1d,
      subjective_feeling_21d,
      im_message_fake_ccr_rate_td,
      before_21d_14d_order_cnt,
      shop_service_ccr_order_cnt_44d_14d,
      cl_inlive_refund_cnt_30d,
      create_order_cnt_30d,
      delivery_order_cnt_1d,
      goods_not_confirm_21d,
      all_severity_penanlize_cnt_90d,
      comment_ccr_td,
      ccr_14d,
      room_cnt,
      is_quality_return_ratio_60d_3_pdc,
      shop_service_bad_eval_rate_7d,
      saling_refund_ucnt_30d,
      aftersale_ccr_180d,
      g_cancel_order_rate_30d,
      saling_refund_order_cnt_1d,
      comment_ccr_14d,
      delivery_order_cnt_30d,
      bad_comment_ratio_60d_3_pdc,
      shop_author_cnt_30d,
      aftersale_fake_ccr_rate_90d,
      pay_gmv_td,
      shop_service_bad_eval_rate_1d,
      live_cnt_30d,
      not_recommend_7d,
      abnormal_price_7d,
      shop_punish_7d,
      video_check_cnt,
      ontime_order_cnt_1d,
      complain_cnt_30d,
      watch_product_click_cnt_ratio_30d,
      ccr_30d,
      intime_res_con_rate_1d,
      ban_severity_penanlize_cnt_60d,
      official_cargo_cnt_30d,
      cancel_gmv_1d,
      good_eval_rate_td,
      create_ucnt_7d,
      all_shop_penanlize_cnt_60d,
      ontime_order_rate_1d,
      aftersale_fake_ccr_180d,
      service_behavior_7d,
      product_bad_eval_rate_7d,
      aftersale_fake_ccr_90d,
      im_message_ccr_14d,
      g_cancel_order_rate_7d,
      product_bad_eval_rate_1d,
      room_check_reject_ratio,
      saled_refund_order_cnt_td,
      shop_ccr_order_cnt_28d_14d,
      ccr_90d,
      low_penanlize_cnt_7d,
      shop_ccr_order_cnt_alld_14d,
      bad_comment_ratio_30d_3_pdc,
      all_penanlize_cnt_180d,
      saled_refund_sucess_gmv_td,
      shop_content_ccr_3d,
      saling_refund_order_cnt_7d,
      promo_fraud_7d,
      complain_rate_7d,
      strong_copy_pdc_30d,
      order_average_price_td,
      report_room_ratio,
      fake_ccr_rate_90d,
      weak_copy_pdc_30d,
      bad_eval_rate_1d,
      create_gmv_td,
      shop_ccr_order_cnt_21d_14d,
      intime_res_con_rate_7d,
      satisfaction_rate_30d,
      shop_content_ccr_order_cnt_28d_14d,
      logistic_good_eval_rate_7d,
      logistic_good_eval_rate_30d,
      fake_ship_order_cnt_td,
      shop_content_ccr_order_cnt_21d_14d,
      fake_ccr_rate_60d,
      alliance_cargo_cnt_7d,
      create_product_cnt_30d,
      shop_punish_30d,
      ban_penanlize_cnt_td,
      aftersale_fake_ccr_td,
      aftersale_fake_ccr_rate_td,
      im_message_fake_ccr_rate_90d,
      channel_cargo_cnt_30d,
      all_product_penanlize_cnt_td,
      saled_refund_ucnt_1d,
      not_recommend_21d,
      forward_logistics_7d,
      im_message_fake_ccr_rate_180d,
      sale_refund_rate_7d,
      fake_ccr_rate_td,
      fake_ccr_rate_180d,
      order_average_price_30d,
      bad_eval_cnt_td,
      aftersale_fake_ccr_30d,
      report_room_cnt,
      audit_success_product_cnt_1d,
      good_eval_rate_30d,
      rescan_white,
      bad_cmn_cnt_7d,
      fake_ccr_90d,
      verify_access_pdc_30d,
      user_average_price_1d,
      cancel_gmv_30d,
      video_check_cnt_7d,
      logistics_timeliness_21d,
      combo_average_price_30d,
      create_order_cnt_7d,
      fake_ccr_rate_30d,
      logistic_bad_eval_cnt_td,
      is_quality_return_ratio_30d_3_pdc,
      shop_service_ccr_order_cnt_28d_14d,
      saling_refund_gmv_30d,
      reject_verify_recall_pdc_7d,
      bad_eval_cnt_30d,
      strong_copy_pdc_7d,
      saled_refund_gmv_30d,
      aftersale_ccr_td,
      service_delivery_21d,
      cancel_ucnt_7d,
      saled_refund_sucess_gmv_30d,
      cancel_gmv_7d,
      saled_refund_sucess_gmv_1d,
      service_delivery_7d,
      shop_service_ccr_order_cnt_21d_14d,
      shop_service_ccr_order_cnt_alld_14d,
      all_product_penanlize_cnt_180d,
      is_clear,
      operate_status,
      product_ban_cnt,
      total_penalize_cnt,
      eval_cnt_30d,
      bad_eval_cnt_7d,
      eval_cnt_7d,
      pay_order_cnt_30d,
      pay_order_cnt_7d,
      good_eval_cnt_30d,
      good_eval_cnt_7d,
      create_order_cnt_td,
      pay_order_cnt_td,
      main_category_new
  FROM  dm_temai.shop_govern_group_stats_for_groupgdfv1 t1
  WHERE   date = max_pt('dm_temai.shop_govern_group_stats_for_groupgdfv1')
),
shop_few_shot_property AS (
  SELECT  shop_id,
      operate_status_code,
      stop_status_code,
      main_vcate,
      main_fcate,
      sqr_30d,
      sqr_ratio_30d,
      xjxc_30d,
      xjxc_ratio_30d,
      sqr_7d,
      sqr_ratio_7d,
      xjxc_7d,
      xjxc_ratio_7d
  FROM  dm_temai.group_few_shot_shop_node_feature
  WHERE   date = max_pt('dm_temai.group_few_shot_shop_node_feature')
)
SELECT  CAST(total_shop.shop_id AS STRING) AS point_id,
    'shop' AS point_type,
    gandalf.quality_return_model,
    gandalf.low_penanlize_cnt_td,
    gandalf.fake_severity_penanlize_cnt_td,
    gandalf.shop_quality_ccr_alld_14d,
    gandalf.ban_severity_penanlize_cnt_td,
    gandalf.audit_success_product_cnt_td,
    gandalf.shop_quality_ccr_order_cnt_14d,
    gandalf.create_ucnt_1d,
    gandalf.g_deport_cnt,
    gandalf.shop_quality_ccr_14d,
    gandalf.g_selfemployed_cnt,
    gandalf.shop_level,
    gandalf.create_gmv_1d,
    gandalf.out_times,
    gandalf.bad_eval_model,
    gandalf.shop_quality_ccr_7d,
    gandalf.g_suspend_cnt,
    gandalf.g_size,
    gandalf.g_bad_eval_rate_30d,
    gandalf.reject_verify_access_pdc,
    gandalf.g_bad_eval_rate_7d,
    gandalf.all_severity_penanlize_cnt_td,
    gandalf.g_open_cnt,
    gandalf.shop_quality_ccr_order_cnt_44d_14d,
    gandalf.create_product_cnt_td,
    gandalf.low_penanlize_cnt_180d,
    gandalf.audit_success_product_cnt_7d,
    gandalf.saled_refund_order_rate_td,
    gandalf.shop_order_cnt_alld_14d,
    gandalf.launch,
    gandalf.shop_quality_ccr_3d,
    gandalf.hit_repeat_distribution_cnt_7d,
    gandalf.received_order_cnt_7d,
    gandalf.aftersale_ccr_14d,
    gandalf.fake_shop_penanlize_cnt_td,
    gandalf.shop_quality_ccr_order_cnt_7d,
    gandalf.g_shop_level_1_cnt,
    gandalf.shop_ccr_alld_14d,
    gandalf.aftersale_ccr_7d,
    gandalf.shop_order_cnt_14d,
    gandalf.cancel_order_rate_td,
    gandalf.g_shop_level_2_cnt,
    gandalf.ontime_order_rate_td,
    gandalf.is_novice_village,
    gandalf.shop_order_cnt_3d,
    gandalf.v_type,
    gandalf.avg_new_response_time_td,
    gandalf.shop_quality_ccr_44d_14d,
    gandalf.shop_content_ccr_7d,
    gandalf.quality_refund_rate_td,
    gandalf.shop_quality_ccr_28d_14d,
    gandalf.is_self_live,
    gandalf.g_product_ban_cnt,
    gandalf.shop_quality_ccr_order_cnt_28d_14d,
    gandalf.class,
    gandalf.g_enterprise_cnt,
    gandalf.satisfaction_rate_1d,
    gandalf.shop_type,
    gandalf.pay_order_rate_7d,
    gandalf.pay_product_cnt_1d_ AS pay_product_cnt_1d_,
    gandalf.shop_content_ccr_alld_14d_ AS shop_content_ccr_alld_14d_,
    gandalf.shop_quality_ccr_order_cnt_alld_14d_ AS shop_quality_ccr_order_cnt_alld_14d_,
    gandalf.shop_quality_ccr_21d_14d_ AS shop_quality_ccr_21d_14d_,
    gandalf.content_cmn_cnt_21d_ AS content_cmn_cnt_21d_,
    gandalf.g_hit_repeat_distribution_cnt_7d,
    gandalf.received_order_cnt_1d,
    gandalf.complain_rate_td,
    gandalf.intime_res_con_rate_td,
    gandalf.pay_order_rate_td,
    gandalf.g_saled_refund_order_rate_30d,
    gandalf.pay_order_rate_30d,
    gandalf.saling_refund_sucess_order_rate_td,
    gandalf.g_total_penalize_cnt,
    gandalf.shop_order_cnt_44d_14d,
    gandalf.avg_new_response_time_30d,
    gandalf.aftersale_ccr_30d,
    gandalf.cancel_order_rate_30d,
    gandalf.shop_service_ccr_7d,
    gandalf.shop_service_21d,
    gandalf.shop_order_cnt_28d_14d,
    gandalf.function_properties_21d,
    gandalf.g_hit_repeat_distribution_cnt_30d,
    gandalf.complaint_model,
    gandalf.shop_quality_ccr_order_cnt_21d_14d,
    gandalf.div_7d,
    gandalf.im_message_ccr_7d,
    gandalf.verify_recall_pdc_7d,
    gandalf.hit_repeat_distribution_cnt_1d,
    gandalf.verify_recall_pdc,
    gandalf.shop_ccr_3d,
    gandalf.product_bad_eval_rate_td,
    gandalf.complain_rate_30d,
    gandalf.saling_refund_order_rate_td,
    gandalf.ontime_order_rate_7d,
    gandalf.all_shop_penanlize_cnt_td,
    gandalf.saled_refund_order_rate_30d,
    gandalf.aftersale_ccr_90d,
    gandalf.aftersale_ccr_60d,
    gandalf.shop_order_cnt_21d_14d,
    gandalf.shop_quality_ccr_order_cnt_3d,
    gandalf.all_severity_penanlize_cnt_180d,
    gandalf.cancel_order_rate_7d,
    gandalf.before_44d_14d_quality_refund_rate,
    gandalf.goods_not_confirm_7d,
    gandalf.pay_ucnt_1d,
    gandalf.pay_product_cnt_30d,
    gandalf.saling_refund_order_rate_30d,
    gandalf.hit_repeat_distribution_cnt_30d,
    gandalf.comment_ccr_7d,
    gandalf.bad_eval_rate_td,
    gandalf.g_saled_refund_order_rate_7d,
    gandalf.video_cnt,
    gandalf.shop_service_bad_eval_rate_td,
    gandalf.shop_content_ccr_44d_14d,
    gandalf.expect_delivery_order_cnt_1d,
    gandalf.shop_settle_type,
    gandalf.saling_refund_ucnt_1d,
    gandalf.pay_product_cnt_7d,
    gandalf.saling_refund_gmv_1d,
    gandalf.logistic_bad_eval_rate_td,
    gandalf.saling_refund_sucess_order_rate_7d,
    gandalf.g_good_eval_rate_30d,
    gandalf.pay_combo_num_30d,
    gandalf.abnormal_pay_gmv_td,
    gandalf.create_order_cnt_1d,
    gandalf.ban_severity_penanlize_cnt_180d,
    gandalf.bad_eval_rate_30d,
    gandalf.report_video_ratio,
    gandalf.hit_repeat_distribution_cnt_td,
    gandalf.light_score,
    gandalf.cancel_order_cnt_7d,
    gandalf.function_properties_7d,
    gandalf.shop_content_ccr_21d_14d,
    gandalf.service_behavior_21d,
    gandalf.video_check_reject_ratio,
    gandalf.pay_gmv_1d,
    gandalf.saled_refund_order_rate_1d,
    gandalf.quality_refund_order_cnt_7d,
    gandalf.logistic_bad_eval_rate_30d,
    gandalf.cancel_ucnt_1d,
    gandalf.pay_product_cnt_td,
    gandalf.shop_service_ccr_order_cnt_14d,
    gandalf.shop_ccr_7d,
    gandalf.combo_average_price_td,
    gandalf.total_alliance_promote_product_cnt,
    gandalf.intime_res_con_rate_30d,
    gandalf.shop_content_ccr_order_cnt_44d_14d,
    gandalf.saled_refund_order_rate_7d,
    gandalf.pay_combo_num_1d,
    gandalf.logistic_bad_eval_rate_7d,
    gandalf.shop_content_ccr_order_cnt_14d,
    gandalf.all_severity_penanlize_cnt_60d,
    gandalf.satisfaction_rate_td,
    gandalf.shop_service_ccr_alld_14d,
    gandalf.shop_content_ccr_28d_14d,
    gandalf.ontime_order_rate_30d,
    gandalf.shop_author_cnt,
    gandalf.reject_verify_access_pdc_7d,
    gandalf.total_alliance_promoted_product_cnt,
    gandalf.avg_watch_duration_30d,
    gandalf.shop_ccr_order_cnt_3d,
    gandalf.shop_service_7d,
    gandalf.all_shop_penanlize_cnt_180d,
    gandalf.shop_service_bad_eval_rate_30d,
    gandalf.shop_content_ccr_order_cnt_7d,
    gandalf.ban_product_cnt_30d,
    gandalf.cancel_order_rate_1d,
    gandalf.create_gmv_30d,
    gandalf.aftersale_fake_ccr_60d,
    gandalf.shop_service_ccr_3d,
    gandalf.before_21d_14d_quality_refund_rate,
    gandalf.abnormal_pay_order_cnt_td,
    gandalf.ccr_7d,
    gandalf.user_average_price_td,
    gandalf.shop_content_ccr_14d,
    gandalf.comment_ccr_180d,
    gandalf.received_order_cnt_30d,
    gandalf.rescan,
    gandalf.video_check_reject_cnt,
    gandalf.content_cmn_cnt_7d,
    gandalf.verify_access_pdc,
    gandalf.saling_refund_sucess_order_rate_30d,
    gandalf.logistic_good_eval_rate_td,
    gandalf.im_message_ccr_60d,
    gandalf.low_penanlize_cnt_90d,
    gandalf.verify_access_pdc_7d,
    gandalf.promo_fraud_21d,
    gandalf.saling_refund_sucess_order_rate_1d,
    gandalf.low_penanlize_cnt_30d,
    gandalf.shop_author_cnt_l5_30d,
    gandalf.shop_service_ccr_44d_14d,
    gandalf.shop_ccr_order_cnt_7d,
    gandalf.product_bad_eval_rate_30d,
    gandalf.bad_eval_rate_7d,
    gandalf.saling_refund_sucess_ucnt_1d,
    gandalf.target_ave_cnt,
    gandalf.subjective_feeling_7d,
    gandalf.shop_ccr_44d_14d,
    gandalf.avg_new_response_time_7d,
    gandalf.quality_refund_order_cnt_td,
    gandalf.im_message_ccr_30d,
    gandalf.shop_service_ccr_21d_14d,
    gandalf.complain_cnt_td,
    gandalf.shop_service_ccr_order_cnt_7d,
    gandalf.audit_success_product_cnt_30d,
    gandalf.saled_refund_order_cnt_30d,
    gandalf.shop_ccr_14d,
    gandalf.reject_verify_recall_pdc_30d,
    gandalf.true_report_room_cnt,
    gandalf.cancel_order_cnt_td,
    gandalf.shop_service_good_eval_rate_td,
    gandalf.expect_delivery_order_cnt_30d,
    gandalf.saling_refund_order_cnt_30d,
    gandalf.ban_product_cnt_td,
    gandalf.reject_verify_recall_pdc,
    gandalf.strong_copy_pdc,
    gandalf.comment_ccr_90d,
    gandalf.saled_refund_sucess_order_cnt_30d,
    gandalf.ban_product_cnt_7d,
    gandalf.forward_logistics_21d,
    gandalf.shop_author_cnt_7d,
    gandalf.saling_refund_sucess_gmv_1d,
    gandalf.im_message_ccr_90d,
    gandalf.video_cnt_7d,
    gandalf.cl_inlive_cancel_cnt_30d,
    gandalf.all_shop_penanlize_cnt_90d,
    gandalf.pay_order_rate_1d,
    gandalf.shop_content_ccr_order_cnt_alld_14d,
    gandalf.weak_copy_pdc,
    gandalf.quality_refund_order_cnt_30d,
    gandalf.avg_watch_duration_7d,
    gandalf.consumer_complaint_7d,
    gandalf.satisfaction_rate_7d,
    gandalf.fake_ship_order_rate_td,
    gandalf.product_good_eval_rate_td,
    gandalf.cancel_order_cnt_1d,
    gandalf.cl_inlive_cancel_cnt_7d,
    gandalf.saling_refund_order_rate_7d,
    gandalf.pay_combo_num_7d,
    gandalf.reject_verify_access_pdc_30d,
    gandalf.create_product_cnt_7d,
    gandalf.video_cnt_30d,
    gandalf.saling_refund_order_cnt_td,
    gandalf.complain_cnt_7d,
    gandalf.saled_refund_order_cnt_7d,
    gandalf.cancel_order_cnt_30d,
    gandalf.shop_ccr_28d_14d,
    gandalf.std,
    gandalf.delivery_order_cnt_7d,
    gandalf.saling_refund_order_rate_1d,
    gandalf.before_44d_14d_order_cnt,
    gandalf.shop_service_ccr_14d,
    gandalf.bad_comment_ratio_30d_2_pdc,
    gandalf.saled_refund_gmv_1d,
    gandalf.shop_author_cnt_l5,
    gandalf.g_good_eval_rate_7d,
    gandalf.illegal_selling_21d,
    gandalf.shop_ccr_21d_14d,
    gandalf.rescan_roll,
    gandalf.customer_experience_7d,
    gandalf.user_average_price_7d,
    gandalf.shop_ccr_order_cnt_14d,
    gandalf.avg_new_response_time_1d,
    gandalf.total_freeze_times_30d,
    gandalf.user_average_price_30d,
    gandalf.verify_recall_pdc_30d,
    gandalf.shop_author_cnt_l5_7d,
    gandalf.consumer_complaint_21d,
    gandalf.cancel_gmv_td,
    gandalf.shop_author_cnt_1d,
    gandalf.subjective_feeling_21d,
    gandalf.im_message_fake_ccr_rate_td,
    gandalf.before_21d_14d_order_cnt,
    gandalf.shop_service_ccr_order_cnt_44d_14d,
    gandalf.cl_inlive_refund_cnt_30d,
    gandalf.create_order_cnt_30d,
    gandalf.delivery_order_cnt_1d,
    gandalf.goods_not_confirm_21d,
    gandalf.all_severity_penanlize_cnt_90d,
    gandalf.comment_ccr_td,
    gandalf.ccr_14d,
    gandalf.room_cnt,
    gandalf.is_quality_return_ratio_60d_3_pdc,
    gandalf.shop_service_bad_eval_rate_7d,
    gandalf.saling_refund_ucnt_30d,
    gandalf.aftersale_ccr_180d,
    gandalf.g_cancel_order_rate_30d,
    gandalf.saling_refund_order_cnt_1d,
    gandalf.comment_ccr_14d,
    gandalf.delivery_order_cnt_30d,
    gandalf.bad_comment_ratio_60d_3_pdc,
    gandalf.shop_author_cnt_30d,
    gandalf.aftersale_fake_ccr_rate_90d,
    gandalf.pay_gmv_td,
    gandalf.shop_service_bad_eval_rate_1d,
    gandalf.live_cnt_30d,
    gandalf.not_recommend_7d,
    gandalf.abnormal_price_7d,
    gandalf.shop_punish_7d,
    gandalf.video_check_cnt,
    gandalf.ontime_order_cnt_1d,
    gandalf.complain_cnt_30d,
    gandalf.watch_product_click_cnt_ratio_30d,
    gandalf.ccr_30d,
    gandalf.intime_res_con_rate_1d,
    gandalf.ban_severity_penanlize_cnt_60d,
    gandalf.official_cargo_cnt_30d,
    gandalf.cancel_gmv_1d,
    gandalf.good_eval_rate_td,
    gandalf.create_ucnt_7d,
    gandalf.all_shop_penanlize_cnt_60d,
    gandalf.ontime_order_rate_1d,
    gandalf.aftersale_fake_ccr_180d,
    gandalf.service_behavior_7d,
    gandalf.product_bad_eval_rate_7d,
    gandalf.aftersale_fake_ccr_90d,
    gandalf.im_message_ccr_14d,
    gandalf.g_cancel_order_rate_7d,
    gandalf.product_bad_eval_rate_1d,
    gandalf.room_check_reject_ratio,
    gandalf.saled_refund_order_cnt_td,
    gandalf.shop_ccr_order_cnt_28d_14d,
    gandalf.ccr_90d,
    gandalf.low_penanlize_cnt_7d,
    gandalf.shop_ccr_order_cnt_alld_14d,
    gandalf.bad_comment_ratio_30d_3_pdc,
    gandalf.all_penanlize_cnt_180d,
    gandalf.saled_refund_sucess_gmv_td,
    gandalf.shop_content_ccr_3d,
    gandalf.saling_refund_order_cnt_7d,
    gandalf.promo_fraud_7d,
    gandalf.complain_rate_7d,
    gandalf.strong_copy_pdc_30d,
    gandalf.order_average_price_td,
    gandalf.report_room_ratio,
    gandalf.fake_ccr_rate_90d,
    gandalf.weak_copy_pdc_30d,
    gandalf.bad_eval_rate_1d,
    gandalf.create_gmv_td,
    gandalf.shop_ccr_order_cnt_21d_14d,
    gandalf.intime_res_con_rate_7d,
    gandalf.satisfaction_rate_30d,
    gandalf.shop_content_ccr_order_cnt_28d_14d,
    gandalf.logistic_good_eval_rate_7d,
    gandalf.logistic_good_eval_rate_30d,
    gandalf.fake_ship_order_cnt_td,
    gandalf.shop_content_ccr_order_cnt_21d_14d,
    gandalf.fake_ccr_rate_60d,
    gandalf.alliance_cargo_cnt_7d,
    gandalf.create_product_cnt_30d,
    gandalf.shop_punish_30d,
    gandalf.ban_penanlize_cnt_td,
    gandalf.aftersale_fake_ccr_td,
    gandalf.aftersale_fake_ccr_rate_td,
    gandalf.im_message_fake_ccr_rate_90d,
    gandalf.channel_cargo_cnt_30d,
    gandalf.all_product_penanlize_cnt_td,
    gandalf.saled_refund_ucnt_1d,
    gandalf.not_recommend_21d,
    gandalf.forward_logistics_7d,
    gandalf.im_message_fake_ccr_rate_180d,
    gandalf.sale_refund_rate_7d,
    gandalf.fake_ccr_rate_td,
    gandalf.fake_ccr_rate_180d,
    gandalf.order_average_price_30d,
    gandalf.bad_eval_cnt_td,
    gandalf.aftersale_fake_ccr_30d,
    gandalf.report_room_cnt,
    gandalf.audit_success_product_cnt_1d,
    gandalf.good_eval_rate_30d,
    gandalf.rescan_white,
    gandalf.bad_cmn_cnt_7d,
    gandalf.fake_ccr_90d,
    gandalf.verify_access_pdc_30d,
    gandalf.user_average_price_1d,
    gandalf.cancel_gmv_30d,
    gandalf.video_check_cnt_7d,
    gandalf.logistics_timeliness_21d,
    gandalf.combo_average_price_30d,
    gandalf.create_order_cnt_7d,
    gandalf.fake_ccr_rate_30d,
    gandalf.logistic_bad_eval_cnt_td,
    gandalf.is_quality_return_ratio_30d_3_pdc,
    gandalf.shop_service_ccr_order_cnt_28d_14d,
    gandalf.saling_refund_gmv_30d,
    gandalf.reject_verify_recall_pdc_7d,
    gandalf.bad_eval_cnt_30d,
    gandalf.strong_copy_pdc_7d,
    gandalf.saled_refund_gmv_30d,
    gandalf.aftersale_ccr_td,
    gandalf.service_delivery_21d,
    gandalf.cancel_ucnt_7d,
    gandalf.saled_refund_sucess_gmv_30d,
    gandalf.cancel_gmv_7d,
    gandalf.saled_refund_sucess_gmv_1d,
    gandalf.service_delivery_7d,
    gandalf.shop_service_ccr_order_cnt_21d_14d,
    gandalf.shop_service_ccr_order_cnt_alld_14d,
    gandalf.all_product_penanlize_cnt_180d,
    gandalf.is_clear,
    gandalf.operate_status,
    gandalf.product_ban_cnt,
    gandalf.total_penalize_cnt,
    gandalf.eval_cnt_30d,
    gandalf.bad_eval_cnt_7d,
    gandalf.eval_cnt_7d,
    gandalf.pay_order_cnt_30d,
    gandalf.pay_order_cnt_7d,
    gandalf.good_eval_cnt_30d,
    gandalf.good_eval_cnt_7d,
    gandalf.create_order_cnt_td,
    gandalf.pay_order_cnt_td,
    gandalf.main_category_new,
    few_shot.operate_status_code,
    few_shot.stop_status_code,
    few_shot.main_vcate,
    few_shot.main_fcate,
    few_shot.sqr_30d,
    few_shot.sqr_ratio_30d,
    few_shot.xjxc_30d,
    few_shot.xjxc_ratio_30d,
    few_shot.sqr_7d,
    few_shot.sqr_ratio_7d,
    few_shot.xjxc_7d,
    few_shot.xjxc_ratio_7d
FROM  total_shop_id_table total_shop
LEFT JOIN
    shop_gandalf_property gandalf
ON    total_shop.shop_id = gandalf.shop_id
LEFT JOIN
    shop_few_shot_property few_shot
ON    total_shop.shop_id = few_shot.shop_id;

SELECT  DISTINCT point_id,
    point_type,
    CASE WHEN a.mediumType = 'id_card' THEN 'idCard'
       WHEN a.mediumType = 'biz_num' THEN 'bizNum'
       WHEN a.mediumType = 'remit_bank' THEN 'bank'
       WHEN a.mediumType = 'quit_bank' THEN 'bank'
       WHEN a.mediumType = 'caijing_bank' THEN 'bank'
       WHEN a.mediumType = 'remit_mobile' THEN 'mobile'
       WHEN a.mediumType = 'aftersale_mobile' THEN 'mobile'
       WHEN a.mediumType = 'quit_mobile' THEN 'mobile'
       WHEN a.mediumType = 'charge_mobile' THEN 'mobile'
       WHEN a.mediumType = 'aftersale2_mobile' THEN 'mobile'
       WHEN a.mediumType = 'pledge_id' THEN 'pledgeId'
       WHEN a.mediumType = '30d_bind_author' THEN 'productBindAuthor'
       WHEN a.mediumType = '30d_send_addr_gh8' THEN 'sendAddr'
       WHEN a.mediumType = '30d_order_product_sim' THEN 'orderProductSim'
       WHEN a.mediumType = '30d_create_product_sim' THEN 'createProductSim'
       WHEN a.mediumType = '30d_order_author' THEN 'orderAuthor'
       WHEN a.mediumType = '30d_login_did' THEN 'loginDid'
       WHEN a.mediumType = '30d_login_ip' THEN 'loginIp'
       ELSE 'undefine'
    END AS mediumType
FROM  (
      SELECT  medium_id AS point_id,
          'medium' AS point_type,
          medium_type AS mediumType
      FROM  dm_temai.shop_hetero_medium
      WHERE   date = max_pt('dm_temai.shop_hetero_medium')
      AND   medium_id IS NOT NULL
      AND   medium_id != ''
      UNION ALL
      SELECT  medium_id AS point_id,
          'medium' AS point_type,
          medium_type AS mediumType
      FROM  dm_temai.shop_hetero_medium_v2
      WHERE   date = max_pt('dm_temai.shop_hetero_medium_v2')
      AND   medium_id IS NOT NULL
      AND   medium_id != ''
    ) a
WHERE   a.mediumType IN (
      'remit_mobile',
      'remit_bank',
      'quit_mobile',
      'quit_bank',
      'pledge_id',
      'id_card',
      'charge_mobile',
      'caijing_bank',
      'biz_num',
      'aftersale_mobile',
      'aftersale2_mobile',
      '30d_bind_author',
      '30d_send_addr_gh8',
      '30d_order_product_sim',
      '30d_create_product_sim',
      '30d_order_author',
      '30d_login_did',
      '30d_login_ip'
    );`, false, nil)
	if err != nil {
		t.Fatalf("RewriteSqls error: %v", err)
	}
	if len(rewritten) != 2 {
		t.Fatalf("expected 2 rewritten sqls, got %d", len(rewritten))
	}

	buffer, _ := json.MarshalIndent(rewritten, "", "  ")
	t.Log("\n" + string(buffer))
}
